name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Racket
        run: |
          sudo apt-get update
          sudo apt-get install -y racket
      - name: Run tests
        run: raco test tests
